# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('dateNaiss', models.CharField(blank=True, max_length=255, null=True)),
                ('lieuNaiss', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('situation_matrimoniale', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('medecin_traitant', models.CharField(blank=True, max_length=255, null=True)),
                ('victime_grave_accident', models.CharField(blank=True, max_length=255, null=True)),
                ('autorisation_medicale_pour_programme_de_fitness_et_muscula', models.CharField(blank=True, max_length=255, null=True)),
                ('autorisation_medicale_pour_programme_de_detente_de_hfc', models.CharField(blank=True, max_length=255, null=True)),
                ('sport_pratique_dans_le_passe', models.CharField(blank=True, max_length=255, null=True)),
                ('sport_pratique_actuellement', models.CharField(blank=True, max_length=255, null=True)),
                ('etat_de_sante', models.CharField(blank=True, max_length=255, null=True)),
                ('problemes_majeurs_a_signaler_imperativement', models.CharField(blank=True, max_length=255, null=True)),
                ('maladies_graves_a_signaler', models.CharField(blank=True, max_length=255, null=True)),
                ('problemes_de_poids', models.CharField(blank=True, max_length=255, null=True)),
                ('coordonnees_completes_de_votre_medecin', models.CharField(blank=True, max_length=255, null=True)),
                ('poids', models.CharField(blank=True, max_length=255, null=True)),
                ('taille', models.CharField(blank=True, max_length=255, null=True)),
                ('rythme_cardiaque', models.CharField(blank=True, max_length=255, null=True)),
                ('tension', models.CharField(blank=True, max_length=255, null=True)),
                ('besoin_specifique_et_attente_chez_hfc', models.CharField(blank=True, max_length=255, null=True)),
                ('souhaitez_vous_un_conseil_et_suivi_pers', models.CharField(blank=True, max_length=255, null=True)),
                ('souhaitez_vous_etre_suivi_par_un_professeur', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_avez_vous_connu_hfc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
